platform :ios, '16.0'

target 'AnisFlix' do
  use_frameworks!

  pod 'google-cast-sdk'
  pod 'MobileVLCKit', '~> 3.6'
  
  # FFmpegKit for Vidzy downloads with custom headers
  # Using community fork (official retired Jan 2025)
  pod 'ffmpeg-kit-ios-full', :podspec => 'https://raw.githubusercontent.com/luthviar/ffmpeg-kit-ios-full/main/ffmpeg-kit-ios-full.podspec'

  # Local Web Server for AirPlay Proxy (Header Injection & Subtitles)
  pod 'GCDWebServer', '~> 3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end

