
import { createDecipheriv } from 'crypto';

const VERCEL_BASE = 'https://anisflix.vercel.app';
const VIDEO_ID = '4m0a4it8eu6q';

function b64urlDecode(str) {
    const base64 = str.replace(/-/g, '+').replace(/_/g, '/');
    const padded = base64.padEnd(base64.length + (4 - base64.length % 4) % 4, '=');
    return Buffer.from(padded, 'base64');
}

function decrypt(keyBuf, ivBuf, payloadBuf) {
    const authTag = payloadBuf.slice(-16);
    const ciphertext = payloadBuf.slice(0, -16);
    const decipher = createDecipheriv('aes-256-gcm', keyBuf, ivBuf);
    decipher.setAuthTag(authTag);
    return Buffer.concat([decipher.update(ciphertext), decipher.final()]).toString('utf-8');
}

async function test() {
    // Step 1: Get playback data from Vercel
    console.log('=== Step 1: Get playback data from Vercel ===');
    const extractResp = await fetch(`${VERCEL_BASE}/api/proxy?action=bysebuho-extract&code=${VIDEO_ID}`);
    const { playback: pb } = await extractResp.json();

    // Step 2: Decrypt payload1 (sprintcdn) - token generated by Vercel IP
    console.log('=== Step 2: Decrypt payload1 (sprintcdn) ===');
    const kp1 = b64urlDecode(pb.key_parts[0]);
    const kp2 = b64urlDecode(pb.key_parts[1]);
    const key1 = Buffer.concat([kp1, kp2]);
    const iv1 = b64urlDecode(pb.iv);
    const payload1 = b64urlDecode(pb.payload);
    const sources1 = JSON.parse(decrypt(key1, iv1, payload1));
    const hls1 = sources1.sources?.filter(s => s.url?.includes('.m3u8'));
    const m3u8Url = (hls1?.find(s => s.quality === 'h') || hls1?.[0])?.url;

    console.log('M3U8 URL:', m3u8Url);
    console.log('ASN in token:', m3u8Url?.match(/asn=([^&]*)/)?.[1] ?? 'not found');

    // Step 3: Test M3U8 via Vercel proxy (same IP as token generation)
    console.log('\n=== Step 3: Test M3U8 via Vercel proxy ===');
    const proxyUrl = `${VERCEL_BASE}/api/proxy?url=${encodeURIComponent(m3u8Url)}&referer=${encodeURIComponent('https://bysebuho.com/')}`;

    const r = await fetch(proxyUrl);
    console.log('Status:', r.status);
    if (r.ok) {
        const text = await r.text();
        console.log('✅ M3U8 content (first 500 chars):');
        console.log(text.substring(0, 500));
    } else {
        const err = await r.text();
        console.log('❌ Error:', err.substring(0, 300));
    }

    // Step 4: Also test direct fetch from local (different IP) to confirm IP-binding
    console.log('\n=== Step 4: Direct fetch from local (different IP) ===');
    const r2 = await fetch(m3u8Url, {
        headers: { 'User-Agent': 'Mozilla/5.0', 'Referer': 'https://bysebuho.com/' }
    });
    console.log('Status:', r2.status, '(should be 404 if IP-bound, 200 if not)');
}

test().catch(console.error);
